import type { Shelter, Rescue } from "./types"

export const mockOrganizations: { shelters: Shelter[]; rescues: Rescue[] } = {
  shelters: [
    {
      id: 1,
      name: "Bay Area Animal Shelter",
      location: "San Francisco, CA",
      distance: "2.3 miles",
      dogsCount: 45,
      urgentCount: 8,
      phone: "(415) 555-0123",
      email: "contact@bayareashelter.org",
      description: "Municipal shelter serving the greater Bay Area with a focus on finding homes for all animals.",
      lat: 37.7749,
      lng: -122.4194,
    },
    {
      id: 2,
      name: "Golden Gate Humane Society",
      location: "Oakland, CA",
      distance: "8.7 miles",
      dogsCount: 32,
      urgentCount: 5,
      phone: "(510) 555-0456",
      email: "help@gghumane.org",
      description: "Non-profit organization dedicated to animal welfare and community education.",
      lat: 37.8044,
      lng: -122.2712,
    },
    {
      id: 3,
      name: "Peninsula Pet Rescue",
      location: "Palo Alto, CA",
      distance: "12.1 miles",
      dogsCount: 28,
      urgentCount: 3,
      phone: "(650) 555-0789",
      email: "info@peninsulapets.org",
      description: "Volunteer-run rescue focusing on senior and special needs animals.",
      lat: 37.4419,
      lng: -122.1430,
    },
  ],
  rescues: [
    {
      id: 1,
      name: "Second Chance Dog Rescue",
      location: "Berkeley, CA",
      distance: "6.4 miles",
      capacity: 15,
      available: 3,
      phone: "(510) 555-0321",
      email: "adopt@secondchancedog.org",
      description: "Specializing in rehabilitating dogs with behavioral challenges and finding them loving homes.",
      lat: 37.8715,
      lng: -122.2730,
    },
    {
      id: 2,
      name: "Loving Paws Sanctuary",
      location: "San Mateo, CA",
      distance: "15.2 miles",
      capacity: 25,
      available: 7,
      phone: "(650) 555-0654",
      email: "contact@lovingpaws.org",
      description: "Foster-based rescue with a network of dedicated volunteers throughout the Bay Area.",
      lat: 37.5630,
      lng: -122.3255,
    },
    {
      id: 3,
      name: "Golden Retriever Rescue",
      location: "San Jose, CA",
      distance: "18.9 miles",
      capacity: 20,
      available: 2,
      phone: "(408) 555-0987",
      email: "info@goldenrescue.org",
      description: "Breed-specific rescue dedicated to Golden Retrievers and Golden mixes.",
      lat: 37.3382,
      lng: -121.8863,
    },
  ],
}