import type { Dog, Shelter, Rescue } from "./types"

export const mockOrganizations: { shelters: Shelter[]; rescues: Rescue[] } = {
  shelters: [
    {
      id: 1,
      name: "Bay Area Animal Shelter",
      location: "San Francisco, CA",
      distance: "2.3 miles",
      dogsCount: 45,
      urgentCount: 8,
      phone: "(415) 555-0123",
      email: "contact@bayareashelter.org",
      description: "Municipal shelter serving the greater Bay Area with a focus on finding homes for all animals.",
      lat: 37.7749,
      lng: -122.4194,
    },
    {
      id: 2,
      name: "Golden Gate Humane Society",
      location: "Oakland, CA",
      distance: "8.7 miles",
      dogsCount: 32,
      urgentCount: 5,
      phone: "(510) 555-0456",
      email: "help@gghumane.org",
      description: "Non-profit organization dedicated to animal welfare and community education.",
      lat: 37.8044,
      lng: -122.2712,
    },
    {
      id: 3,
      name: "Peninsula Pet Rescue",
      location: "Palo Alto, CA",
      distance: "12.1 miles",
      dogsCount: 28,
      urgentCount: 3,
      phone: "(650) 555-0789",
      email: "info@peninsulapets.org",
      description: "Volunteer-run rescue focusing on senior and special needs animals.",
      lat: 37.4419,
      lng: -122.1430,
    },
  ],
  rescues: [
    {
      id: 1,
      name: "Second Chance Dog Rescue",
      location: "Berkeley, CA",
      distance: "6.4 miles",
      capacity: 15,
      available: 3,
      phone: "(510) 555-0321",
      email: "adopt@secondchancedog.org",
      description: "Specializing in rehabilitating dogs with behavioral challenges and finding them loving homes.",
      lat: 37.8715,
      lng: -122.2730,
    },
    {
      id: 2,
      name: "Loving Paws Sanctuary",
      location: "San Mateo, CA",
      distance: "15.2 miles",
      capacity: 25,
      available: 7,
      phone: "(650) 555-0654",
      email: "contact@lovingpaws.org",
      description: "Foster-based rescue with a network of dedicated volunteers throughout the Bay Area.",
      lat: 37.5630,
      lng: -122.3255,
    },
    {
      id: 3,
      name: "Golden Retriever Rescue",
      location: "San Jose, CA",
      distance: "18.9 miles",
      capacity: 20,
      available: 2,
      phone: "(408) 555-0987",
      email: "info@goldenrescue.org",
      description: "Breed-specific rescue dedicated to Golden Retrievers and Golden mixes.",
      lat: 37.3382,
      lng: -121.8863,
    },
  ],
}

export const mockDogs: Dog[] = [
  {
    id: 70000001, // Changed to a large number to simulate a real Petfinder ID
    name: "Buddy",
    breed: "Golden Retriever",
    age: "2 years",
    gender: "Male",
    shelter: "Bay Area Animal Shelter",
    distance: "2.3 miles",
    photos: [{
      small: "https://placedog.net/200/200?id=1",
      medium: "https://placedog.net/500/500?id=1",
      large: "https://placedog.net/800/800?id=1",
      full: "https://placedog.net/1200/1200?id=1",
    }],
    urgent: true,
    description: "A friendly and energetic boy who loves to play fetch and swim. He's great with other dogs and would thrive in an active home. Buddy is house-trained and knows basic commands.",
    characteristics: ["Athletic", "Affectionate", "Playful", "Friendly", "Smart"],
    health: ["Vaccinations up to date", "Spayed / Neutered"],
    goodInHomeWith: ["Other dogs", "Children"],
    adoptionFee: 300,
  },
  {
    id: 70000002, // Changed to a large number
    name: "Luna",
    breed: "German Shepherd Mix",
    age: "1 year",
    gender: "Female",
    shelter: "Golden Gate Humane Society",
    distance: "8.7 miles",
    photos: [{
      small: "https://placedog.net/200/200?id=2",
      medium: "https://placedog.net/500/500?id=2",
      large: "https://placedog.net/800/800?id=2",
      full: "https://placedog.net/1200/1200?id=2",
    }],
    urgent: false,
    description: "A smart and loyal companion, great with kids and other dogs. Luna is eager to please and would benefit from continued training. She loves long walks and puzzle toys.",
    characteristics: ["Smart", "Loyal", "Curious", "Friendly"],
    health: ["Vaccinations up to date", "Spayed / Neutered"],
    goodInHomeWith: ["Other dogs", "Children"],
    adoptionFee: 350,
  },
  {
    id: 70000003, // Changed to a large number
    name: "Max",
    breed: "Beagle",
    age: "4 years",
    gender: "Male",
    shelter: "Peninsula Pet Rescue",
    distance: "12.1 miles",
    photos: [{
      small: "https://placedog.net/200/200?id=3",
      medium: "https://placedog.net/500/500?id=3",
      large: "https://placedog.net/800/800?id=3",
      full: "https://placedog.net/1200/1200?id=3",
    }],
    urgent: false,
    description: "A curious and happy-go-lucky dog who loves to follow his nose. Max is a typical beagle, full of personality and loves to explore. He's looking for a home with a secure yard.",
    characteristics: ["Curious", "Funny", "Independent"],
    health: ["Vaccinations up to date", "Spayed / Neutered"],
    goodInHomeWith: ["Other dogs"],
    adoptionFee: 250,
  },
  {
    id: 70000004, // Changed to a large number
    name: "Daisy",
    breed: "Pit Bull Mix",
    age: "3 years",
    gender: "Female",
    shelter: "Bay Area Animal Shelter",
    distance: "2.3 miles",
    photos: [{
      small: "https://placedog.net/200/200?id=4",
      medium: "https://placedog.net/500/500?id=4",
      large: "https://placedog.net/800/800?id=4",
      full: "https://placedog.net/1200/1200?id=4",
    }],
    urgent: true,
    description: "A sweet and affectionate girl who just wants to cuddle on the couch. Daisy is a gentle soul who enjoys quiet evenings and soft blankets. She's looking for a calm home.",
    characteristics: ["Affectionate", "Gentle", "Calm"],
    health: ["Vaccinations up to date", "Spayed / Neutered"],
    goodInHomeWith: ["Children"],
    adoptionFee: 275,
  },
  {
    id: 70000005, // Changed to a large number
    name: "Rocky",
    breed: "Labrador Mix",
    age: "5 years",
    gender: "Male",
    shelter: "Loving Paws Sanctuary",
    distance: "15.2 miles",
    photos: [{
      small: "https://placedog.net/200/200?id=5",
      medium: "https://placedog.net/500/500?id=5",
      large: "https://placedog.net/800/800?id=5",
      full: "https://placedog.net/1200/1200?id=5",
    }],
    urgent: false,
    description: "A gentle giant who is calm, well-behaved, and loves long walks. Rocky is a laid-back dog who enjoys leisurely strolls and napping in sunbeams. He's a perfect family dog.",
    characteristics: ["Calm", "Gentle", "Well-behaved"],
    health: ["Vaccinations up to date", "Spayed / Neutered"],
    goodInHomeWith: ["Other dogs", "Children"],
    adoptionFee: 320,
  },
  {
    id: 70000006, // Changed to a large number
    name: "Sadie",
    breed: "Australian Shepherd",
    age: "1.5 years",
    gender: "Female",
    shelter: "Golden Gate Humane Society",
    distance: "8.7 miles",
    photos: [{
      small: "https://placedog.net/200/200?id=6",
      medium: "https://placedog.net/500/500?id=6",
      large: "https://placedog.net/800/800?id=6",
      full: "https://placedog.net/1200/1200?id=6",
    }],
    urgent: false,
    description: "A highly intelligent and active dog, perfect for an adventurous family. Sadie thrives on mental and physical stimulation. She would excel in a home that enjoys hiking or dog sports.",
    characteristics: ["Intelligent", "Active", "Brave", "Playful"],
    health: ["Vaccinations up to date", "Spayed / Neutered"],
    goodInHomeWith: ["Other dogs"],
    adoptionFee: 380,
  },
]