import type { Dog, Shelter, Rescue } from "./types"

export const mockOrganizations: { shelters: Shelter[]; rescues: Rescue[] } = {
  shelters: [
    {
      id: 1,
      name: "Bay Area Animal Shelter",
      location: "San Francisco, CA",
      distance: "2.3 miles",
      dogsCount: 45,
      urgentCount: 8,
      phone: "(415) 555-0123",
      email: "contact@bayareashelter.org",
      description: "Municipal shelter serving the greater Bay Area with a focus on finding homes for all animals.",
    },
    {
      id: 2,
      name: "Golden Gate Humane Society",
      location: "Oakland, CA",
      distance: "8.7 miles",
      dogsCount: 32,
      urgentCount: 5,
      phone: "(510) 555-0456",
      email: "help@gghumane.org",
      description: "Non-profit organization dedicated to animal welfare and community education.",
    },
    {
      id: 3,
      name: "Peninsula Pet Rescue",
      location: "Palo Alto, CA",
      distance: "12.1 miles",
      dogsCount: 28,
      urgentCount: 3,
      phone: "(650) 555-0789",
      email: "info@peninsulapets.org",
      description: "Volunteer-run rescue focusing on senior and special needs animals.",
    },
  ],
  rescues: [
    {
      id: 1,
      name: "Second Chance Dog Rescue",
      location: "Berkeley, CA",
      distance: "6.4 miles",
      capacity: 15,
      available: 3,
      phone: "(510) 555-0321",
      email: "adopt@secondchancedog.org",
      description: "Specializing in rehabilitating dogs with behavioral challenges and finding them loving homes.",
    },
    {
      id: 2,
      name: "Loving Paws Sanctuary",
      location: "San Mateo, CA",
      distance: "15.2 miles",
      capacity: 25,
      available: 7,
      phone: "(650) 555-0654",
      email: "contact@lovingpaws.org",
      description: "Foster-based rescue with a network of dedicated volunteers throughout the Bay Area.",
    },
    {
      id: 3,
      name: "Golden Retriever Rescue",
      location: "San Jose, CA",
      distance: "18.9 miles",
      capacity: 20,
      available: 2,
      phone: "(408) 555-0987",
      email: "info@goldenrescue.org",
      description: "Breed-specific rescue dedicated to Golden Retrievers and Golden mixes.",
    },
  ],
}

export const mockDogs: Dog[] = [
  {
    id: 1,
    name: "Buddy",
    breed: "Golden Retriever",
    age: "2 years",
    gender: "Male",
    shelter: "Bay Area Animal Shelter",
    distance: "2.3 miles",
    image: "https://placedog.net/500/500?id=1",
    urgent: true,
    description: "A friendly and energetic boy who loves to play fetch and swim.",
  },
  {
    id: 2,
    name: "Luna",
    breed: "German Shepherd Mix",
    age: "1 year",
    gender: "Female",
    shelter: "Golden Gate Humane Society",
    distance: "8.7 miles",
    image: "https://placedog.net/500/500?id=2",
    urgent: false,
    description: "A smart and loyal companion, great with kids and other dogs.",
  },
  {
    id: 3,
    name: "Max",
    breed: "Beagle",
    age: "4 years",
    gender: "Male",
    shelter: "Peninsula Pet Rescue",
    distance: "12.1 miles",
    image: "https://placedog.net/500/500?id=3",
    urgent: false,
    description: "A curious and happy-go-lucky dog who loves to follow his nose.",
  },
  {
    id: 4,
    name: "Daisy",
    breed: "Pit Bull Mix",
    age: "3 years",
    gender: "Female",
    shelter: "Bay Area Animal Shelter",
    distance: "2.3 miles",
    image: "https://placedog.net/500/500?id=4",
    urgent: true,
    description: "A sweet and affectionate girl who just wants to cuddle on the couch.",
  },
  {
    id: 5,
    name: "Rocky",
    breed: "Labrador Mix",
    age: "5 years",
    gender: "Male",
    shelter: "Loving Paws Sanctuary",
    distance: "15.2 miles",
    image: "https://placedog.net/500/500?id=5",
    urgent: false,
    description: "A gentle giant who is calm, well-behaved, and loves long walks.",
  },
  {
    id: 6,
    name: "Sadie",
    breed: "Australian Shepherd",
    age: "1.5 years",
    gender: "Female",
    shelter: "Golden Gate Humane Society",
    distance: "8.7 miles",
    image: "https://placedog.net/500/500?id=6",
    urgent: false,
    description: "A highly intelligent and active dog, perfect for an adventurous family.",
  },
]